services:
  app:
    image: ghcr.io/suzuki3jp/imba # TODO: ${IMAGE_FULL} でやっても読み込みに失敗したため応急処置的にlatest指定
    container_name: imba
    ports:
      - '1111:1111'
    volumes:
      - ./.env:/usr/src/app/.env
      - ./config.json:/usr/src/app/dist/data/config.json
    stdin_open: true
    tty: true
    restart: unless-stopped
